// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokerTrackerApi.HandHistories;
using PokerTrackerApi.Persistence;

#nullable disable

namespace PokerTrackerApi.Persistence.Migrations
{
    [DbContext(typeof(PokerTrackerDbContext))]
    [Migration("20260930154833_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PokerTrackerApi.HandHistories.ParsedHand", b =>
                {
                    b.Property<string>("HandId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("HandId");

                    b.ToTable("ParsedHands");
                });

            modelBuilder.Entity("PokerTrackerApi.HandHistories.RawHand", b =>
                {
                    b.Property<string>("HandId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("HandId");

                    b.ToTable("RawHands");
                });

            modelBuilder.Entity("PokerTrackerApi.HandHistories.ParsedHand", b =>
                {
                    b.HasOne("PokerTrackerApi.HandHistories.RawHand", null)
                        .WithOne()
                        .HasForeignKey("PokerTrackerApi.HandHistories.ParsedHand", "HandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
