// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokerTrackerApi.Persistence;

#nullable disable

namespace PokerTrackerApi.Persistence.Migrations
{
    [DbContext(typeof(PokerTrackerDbContext))]
    [Migration("20261008204656_AddRiverBetResponseLines")]
    partial class AddRiverBetResponseLines
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandEvent", b =>
                {
                    b.Property<string>("HandId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("HandId", "Sequence");

                    b.ToTable("PokerHandEvents");

                    b.HasDiscriminator<string>("EventType").HasValue("PokerHandEvent");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.PokerHand", b =>
                {
                    b.Property<string>("HandId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("HeroPlayerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.ComplexProperty<Dictionary<string, object>>("HeroHoleCards", "PokerTrackerApi.Domain.PokerHand.PokerHand.HeroHoleCards#HoleCards", b1 =>
                        {
                            b1.IsRequired();

                            b1.ComplexProperty<Dictionary<string, object>>("First", "PokerTrackerApi.Domain.PokerHand.PokerHand.HeroHoleCards#HoleCards.First#PlayingCard", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<int>("Rank")
                                        .HasColumnType("int");

                                    b2.Property<int>("Suit")
                                        .HasColumnType("int");
                                });

                            b1.ComplexProperty<Dictionary<string, object>>("Second", "PokerTrackerApi.Domain.PokerHand.PokerHand.HeroHoleCards#HoleCards.Second#PlayingCard", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<int>("Rank")
                                        .HasColumnType("int");

                                    b2.Property<int>("Suit")
                                        .HasColumnType("int");
                                });
                        });

                    b.HasKey("HandId");

                    b.ToTable("PokerHands");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.PokerHandPlayer", b =>
                {
                    b.Property<string>("HandId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("PlayerId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<decimal>("StartingStackBB")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("HandId", "PlayerId");

                    b.ToTable("PokerHandPlayers");
                });

            modelBuilder.Entity("PokerTrackerApi.HandAnnotations.HandAnnotation", b =>
                {
                    b.Property<string>("HandId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<bool>("Flagged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("HandId");

                    b.ToTable("HandAnnotations");
                });

            modelBuilder.Entity("PokerTrackerApi.HandAnnotations.HandLabelAssignment", b =>
                {
                    b.Property<string>("HandId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Street")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Label")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("HandId", "Street", "Label");

                    b.HasIndex("Label", "HandId");

                    b.ToTable("HandLabelAssignments");
                });

            modelBuilder.Entity("PokerTrackerApi.HandImporting.Jobs.HandImportJob", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.HasKey("JobId");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("HandImportJobs");
                });

            modelBuilder.Entity("PokerTrackerApi.HandImporting.Jobs.HandImportJobFile", b =>
                {
                    b.Property<Guid>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<int>("DuplicateHands")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("HandsSaved")
                        .HasColumnType("int");

                    b.Property<int>("InvalidHands")
                        .HasColumnType("int");

                    b.Property<Guid>("JobId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("FileId");

                    b.HasIndex("JobId", "Sequence")
                        .IsUnique();

                    b.HasIndex("Status", "LeaseExpiresAt");

                    b.ToTable("HandImportJobFiles");
                });

            modelBuilder.Entity("PokerTrackerApi.HandImporting.RawHand", b =>
                {
                    b.Property<string>("HandId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("HandId");

                    b.ToTable("RawHands");
                });

            modelBuilder.Entity("PokerTrackerApi.MassData.MassDataReprocessingJob", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext");

                    b.Property<string>("LastProcessedHandId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProcessedHands")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<int>("TotalHands")
                        .HasColumnType("int");

                    b.HasKey("JobId");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("MassDataReprocessingJobs");
                });

            modelBuilder.Entity("PokerTrackerApi.MassData.PostflopBettingSpot", b =>
                {
                    b.Property<string>("HandId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Street")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("DefendingPlayerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DefendingPosition")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<decimal?>("DonkBetBb")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)");

                    b.Property<string>("FlopActionSequence")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("FlopHighCard")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("FlopRankTexture")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("FlopTexture")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<bool>("FlopWentCheckCheck")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset>("HandTimestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("HeroCalledVillainRiverBet")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HeroCalledVillainRiverRaise")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("HeroPlayerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("HeroResponseToVillainRiverBet")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("HeroResponseToVillainRiverRaise")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<decimal?>("HeroRiverBetToPotRatio")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<decimal?>("PfrBetBb")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)");

                    b.Property<bool>("PfrInPosition")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PfrPlayerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PfrPosition")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<int>("PreflopRaiseCount")
                        .HasColumnType("int");

                    b.Property<string>("ResponseAction")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<decimal?>("ResponseAmountBb")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)");

                    b.Property<string>("ResponseTo")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("RiverBetResponseLine")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<decimal?>("RiverBetToPotRatio")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<string>("RiverRunout")
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<string>("RiverShowdownOutcome")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<bool>("RiverWentToShowdown")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TurnActionSequence")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("TurnRunout")
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<string>("VillainResponseToHeroRiverBet")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<bool>("VillainRiverBet")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("VillainRiverBetShowdownOutcome")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<bool>("VillainRiverRaise")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("VillainRiverRaiseShowdownOutcome")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.HasKey("HandId", "Street");

                    b.HasIndex("Street", "FlopActionSequence");

                    b.HasIndex("Street", "FlopHighCard");

                    b.HasIndex("Street", "FlopRankTexture");

                    b.HasIndex("Street", "FlopTexture");

                    b.HasIndex("Street", "RiverRunout");

                    b.HasIndex("Street", "TurnActionSequence");

                    b.HasIndex("Street", "TurnRunout");

                    b.HasIndex("Street", "PreflopRaiseCount", "FlopWentCheckCheck");

                    b.ToTable("PostflopBettingSpots");
                });

            modelBuilder.Entity("PokerTrackerApi.PreflopSpots.PreflopSpot", b =>
                {
                    b.Property<string>("HandId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("SpotKey")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("HandKey")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.HasKey("HandId", "SpotKey");

                    b.HasIndex("SpotKey", "HandKey", "Action");

                    b.ToTable("PreflopSpots");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandBoardDealtEvent", b =>
                {
                    b.HasBaseType("PokerTrackerApi.Domain.PokerHand.Events.PokerHandEvent");

                    b.Property<int>("Street")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("PokerHandBoardDealtEvent");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandCardsShownEvent", b =>
                {
                    b.HasBaseType("PokerTrackerApi.Domain.PokerHand.Events.PokerHandEvent");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.ComplexProperty<Dictionary<string, object>>("HoleCards", "PokerTrackerApi.Domain.PokerHand.Events.PokerHandCardsShownEvent.HoleCards#HoleCards", b1 =>
                        {
                            b1.IsRequired();

                            b1.ComplexProperty<Dictionary<string, object>>("First", "PokerTrackerApi.Domain.PokerHand.Events.PokerHandCardsShownEvent.HoleCards#HoleCards.First#PlayingCard", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<int>("Rank")
                                        .HasColumnType("int");

                                    b2.Property<int>("Suit")
                                        .HasColumnType("int");
                                });

                            b1.ComplexProperty<Dictionary<string, object>>("Second", "PokerTrackerApi.Domain.PokerHand.Events.PokerHandCardsShownEvent.HoleCards#HoleCards.Second#PlayingCard", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<int>("Rank")
                                        .HasColumnType("int");

                                    b2.Property<int>("Suit")
                                        .HasColumnType("int");
                                });
                        });

                    b.HasDiscriminator().HasValue("CardsShown");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandCashDropEvent", b =>
                {
                    b.HasBaseType("PokerTrackerApi.Domain.PokerHand.Events.PokerHandEvent");

                    b.Property<decimal>("AmountBB")
                        .HasColumnType("decimal(65,30)");

                    b.HasDiscriminator().HasValue("CashDrop");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandPlayerActionEvent", b =>
                {
                    b.HasBaseType("PokerTrackerApi.Domain.PokerHand.Events.PokerHandEvent");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.ToTable("PokerHandEvents", t =>
                        {
                            t.Property("PlayerId")
                                .HasColumnName("PokerHandPlayerActionEvent_PlayerId");
                        });

                    b.HasDiscriminator().HasValue("PokerHandPlayerActionEvent");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandPostEvent", b =>
                {
                    b.HasBaseType("PokerTrackerApi.Domain.PokerHand.Events.PokerHandEvent");

                    b.Property<decimal>("AmountBB")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("PostType")
                        .HasColumnType("int");

                    b.ToTable("PokerHandEvents", t =>
                        {
                            t.Property("AmountBB")
                                .HasColumnName("PokerHandPostEvent_AmountBB");

                            t.Property("PlayerId")
                                .HasColumnName("PokerHandPostEvent_PlayerId");
                        });

                    b.HasDiscriminator().HasValue("PokerHandPostEvent");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandPotAwardedEvent", b =>
                {
                    b.HasBaseType("PokerTrackerApi.Domain.PokerHand.Events.PokerHandEvent");

                    b.Property<decimal>("AmountBB")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.ToTable("PokerHandEvents", t =>
                        {
                            t.Property("AmountBB")
                                .HasColumnName("PokerHandPotAwardedEvent_AmountBB");

                            t.Property("PlayerId")
                                .HasColumnName("PokerHandPotAwardedEvent_PlayerId");
                        });

                    b.HasDiscriminator().HasValue("PotAwarded");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandUncalledBetReturnedEvent", b =>
                {
                    b.HasBaseType("PokerTrackerApi.Domain.PokerHand.Events.PokerHandEvent");

                    b.Property<decimal>("AmountBB")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.ToTable("PokerHandEvents", t =>
                        {
                            t.Property("AmountBB")
                                .HasColumnName("PokerHandUncalledBetReturnedEvent_AmountBB");

                            t.Property("PlayerId")
                                .HasColumnName("PokerHandUncalledBetReturnedEvent_PlayerId");
                        });

                    b.HasDiscriminator().HasValue("UncalledBetReturned");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandFlopDealtEvent", b =>
                {
                    b.HasBaseType("PokerTrackerApi.Domain.PokerHand.Events.PokerHandBoardDealtEvent");

                    b.ComplexProperty<Dictionary<string, object>>("First", "PokerTrackerApi.Domain.PokerHand.Events.PokerHandFlopDealtEvent.First#PlayingCard", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Rank")
                                .HasColumnType("int");

                            b1.Property<int>("Suit")
                                .HasColumnType("int");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Second", "PokerTrackerApi.Domain.PokerHand.Events.PokerHandFlopDealtEvent.Second#PlayingCard", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Rank")
                                .HasColumnType("int");

                            b1.Property<int>("Suit")
                                .HasColumnType("int");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Third", "PokerTrackerApi.Domain.PokerHand.Events.PokerHandFlopDealtEvent.Third#PlayingCard", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Rank")
                                .HasColumnType("int");

                            b1.Property<int>("Suit")
                                .HasColumnType("int");
                        });

                    b.HasDiscriminator().HasValue("FlopDealt");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandRiverDealtEvent", b =>
                {
                    b.HasBaseType("PokerTrackerApi.Domain.PokerHand.Events.PokerHandBoardDealtEvent");

                    b.ComplexProperty<Dictionary<string, object>>("Card", "PokerTrackerApi.Domain.PokerHand.Events.PokerHandRiverDealtEvent.Card#PlayingCard", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Rank")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("int");

                            b1.Property<int>("Suit")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("int");
                        });

                    b.HasDiscriminator().HasValue("RiverDealt");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandTurnDealtEvent", b =>
                {
                    b.HasBaseType("PokerTrackerApi.Domain.PokerHand.Events.PokerHandBoardDealtEvent");

                    b.ComplexProperty<Dictionary<string, object>>("Card", "PokerTrackerApi.Domain.PokerHand.Events.PokerHandTurnDealtEvent.Card#PlayingCard", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Rank")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("int");

                            b1.Property<int>("Suit")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("int");
                        });

                    b.HasDiscriminator().HasValue("TurnDealt");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandPlayerBetEvent", b =>
                {
                    b.HasBaseType("PokerTrackerApi.Domain.PokerHand.Events.PokerHandPlayerActionEvent");

                    b.Property<decimal>("BetAmountBB")
                        .HasColumnType("decimal(65,30)");

                    b.ToTable("PokerHandEvents", t =>
                        {
                            t.Property("PlayerId")
                                .HasColumnName("PokerHandPlayerActionEvent_PlayerId");
                        });

                    b.HasDiscriminator().HasValue("PlayerBet");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandPlayerCallEvent", b =>
                {
                    b.HasBaseType("PokerTrackerApi.Domain.PokerHand.Events.PokerHandPlayerActionEvent");

                    b.Property<decimal>("CallAmountBB")
                        .HasColumnType("decimal(65,30)");

                    b.ToTable("PokerHandEvents", t =>
                        {
                            t.Property("PlayerId")
                                .HasColumnName("PokerHandPlayerActionEvent_PlayerId");
                        });

                    b.HasDiscriminator().HasValue("PlayerCall");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandPlayerCheckEvent", b =>
                {
                    b.HasBaseType("PokerTrackerApi.Domain.PokerHand.Events.PokerHandPlayerActionEvent");

                    b.ToTable("PokerHandEvents", t =>
                        {
                            t.Property("PlayerId")
                                .HasColumnName("PokerHandPlayerActionEvent_PlayerId");
                        });

                    b.HasDiscriminator().HasValue("PlayerCheck");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandPlayerFoldEvent", b =>
                {
                    b.HasBaseType("PokerTrackerApi.Domain.PokerHand.Events.PokerHandPlayerActionEvent");

                    b.ToTable("PokerHandEvents", t =>
                        {
                            t.Property("PlayerId")
                                .HasColumnName("PokerHandPlayerActionEvent_PlayerId");
                        });

                    b.HasDiscriminator().HasValue("PlayerFold");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandPlayerRaiseEvent", b =>
                {
                    b.HasBaseType("PokerTrackerApi.Domain.PokerHand.Events.PokerHandPlayerActionEvent");

                    b.Property<bool>("IsAllIn")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("RaiseAmountBB")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("RaiseToAmountBB")
                        .HasColumnType("decimal(65,30)");

                    b.ToTable("PokerHandEvents", t =>
                        {
                            t.Property("PlayerId")
                                .HasColumnName("PokerHandPlayerActionEvent_PlayerId");
                        });

                    b.HasDiscriminator().HasValue("PlayerRaise");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandAntePostEvent", b =>
                {
                    b.HasBaseType("PokerTrackerApi.Domain.PokerHand.Events.PokerHandPostEvent");

                    b.ToTable("PokerHandEvents", t =>
                        {
                            t.Property("AmountBB")
                                .HasColumnName("PokerHandPostEvent_AmountBB");

                            t.Property("PlayerId")
                                .HasColumnName("PokerHandPostEvent_PlayerId");
                        });

                    b.HasDiscriminator().HasValue("AntePost");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandBigBlindPostEvent", b =>
                {
                    b.HasBaseType("PokerTrackerApi.Domain.PokerHand.Events.PokerHandPostEvent");

                    b.ToTable("PokerHandEvents", t =>
                        {
                            t.Property("AmountBB")
                                .HasColumnName("PokerHandPostEvent_AmountBB");

                            t.Property("PlayerId")
                                .HasColumnName("PokerHandPostEvent_PlayerId");
                        });

                    b.HasDiscriminator().HasValue("BigBlindPost");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandSmallBlindPostEvent", b =>
                {
                    b.HasBaseType("PokerTrackerApi.Domain.PokerHand.Events.PokerHandPostEvent");

                    b.ToTable("PokerHandEvents", t =>
                        {
                            t.Property("AmountBB")
                                .HasColumnName("PokerHandPostEvent_AmountBB");

                            t.Property("PlayerId")
                                .HasColumnName("PokerHandPostEvent_PlayerId");
                        });

                    b.HasDiscriminator().HasValue("SmallBlindPost");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandEvent", b =>
                {
                    b.HasOne("PokerTrackerApi.Domain.PokerHand.PokerHand", null)
                        .WithMany("Events")
                        .HasForeignKey("HandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.PokerHand", b =>
                {
                    b.HasOne("PokerTrackerApi.HandImporting.RawHand", null)
                        .WithOne()
                        .HasForeignKey("PokerTrackerApi.Domain.PokerHand.PokerHand", "HandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.PokerHandPlayer", b =>
                {
                    b.HasOne("PokerTrackerApi.Domain.PokerHand.PokerHand", null)
                        .WithMany("Players")
                        .HasForeignKey("HandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokerTrackerApi.HandAnnotations.HandAnnotation", b =>
                {
                    b.HasOne("PokerTrackerApi.HandImporting.RawHand", null)
                        .WithMany()
                        .HasForeignKey("HandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokerTrackerApi.HandAnnotations.HandLabelAssignment", b =>
                {
                    b.HasOne("PokerTrackerApi.Domain.PokerHand.PokerHand", null)
                        .WithMany()
                        .HasForeignKey("HandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokerTrackerApi.HandImporting.Jobs.HandImportJobFile", b =>
                {
                    b.HasOne("PokerTrackerApi.HandImporting.Jobs.HandImportJob", null)
                        .WithMany("Files")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokerTrackerApi.MassData.PostflopBettingSpot", b =>
                {
                    b.HasOne("PokerTrackerApi.Domain.PokerHand.PokerHand", null)
                        .WithMany()
                        .HasForeignKey("HandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokerTrackerApi.PreflopSpots.PreflopSpot", b =>
                {
                    b.HasOne("PokerTrackerApi.HandImporting.RawHand", null)
                        .WithMany()
                        .HasForeignKey("HandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.PokerHand", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("PokerTrackerApi.HandImporting.Jobs.HandImportJob", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
