// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokerTrackerApi.Persistence;

#nullable disable

namespace PokerTrackerApi.Persistence.Migrations
{
    [DbContext(typeof(PokerTrackerDbContext))]
    [Migration("20261004162720_MigrateToPokerHand")]
    partial class MigrateToPokerHand
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandEvent", b =>
                {
                    b.Property<string>("HandId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("HandId", "Sequence");

                    b.ToTable("PokerHandEvents");

                    b.HasDiscriminator<string>("EventType").HasValue("PokerHandEvent");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.PokerHand", b =>
                {
                    b.Property<string>("HandId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("HeroPlayerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.ComplexProperty<Dictionary<string, object>>("HeroHoleCards", "PokerTrackerApi.Domain.PokerHand.PokerHand.HeroHoleCards#HoleCards", b1 =>
                        {
                            b1.IsRequired();

                            b1.ComplexProperty<Dictionary<string, object>>("First", "PokerTrackerApi.Domain.PokerHand.PokerHand.HeroHoleCards#HoleCards.First#PlayingCard", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<int>("Rank")
                                        .HasColumnType("int");

                                    b2.Property<int>("Suit")
                                        .HasColumnType("int");
                                });

                            b1.ComplexProperty<Dictionary<string, object>>("Second", "PokerTrackerApi.Domain.PokerHand.PokerHand.HeroHoleCards#HoleCards.Second#PlayingCard", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<int>("Rank")
                                        .HasColumnType("int");

                                    b2.Property<int>("Suit")
                                        .HasColumnType("int");
                                });
                        });

                    b.HasKey("HandId");

                    b.ToTable("PokerHands");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.PokerHandPlayer", b =>
                {
                    b.Property<string>("HandId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("PlayerId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<decimal>("StartingStackBB")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("HandId", "PlayerId");

                    b.ToTable("PokerHandPlayers");
                });

            modelBuilder.Entity("PokerTrackerApi.HandImports.RawHand", b =>
                {
                    b.Property<string>("HandId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("HandId");

                    b.ToTable("RawHands");
                });

            modelBuilder.Entity("PokerTrackerApi.PreflopSpots.PreflopSpot", b =>
                {
                    b.Property<string>("HandId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("SpotKey")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("HandKey")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.HasKey("HandId", "SpotKey");

                    b.HasIndex("SpotKey", "HandKey", "Action");

                    b.ToTable("PreflopSpots");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandBoardDealtEvent", b =>
                {
                    b.HasBaseType("PokerTrackerApi.Domain.PokerHand.Events.PokerHandEvent");

                    b.Property<int>("Street")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("PokerHandBoardDealtEvent");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandCardsShownEvent", b =>
                {
                    b.HasBaseType("PokerTrackerApi.Domain.PokerHand.Events.PokerHandEvent");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.ComplexProperty<Dictionary<string, object>>("HoleCards", "PokerTrackerApi.Domain.PokerHand.Events.PokerHandCardsShownEvent.HoleCards#HoleCards", b1 =>
                        {
                            b1.IsRequired();

                            b1.ComplexProperty<Dictionary<string, object>>("First", "PokerTrackerApi.Domain.PokerHand.Events.PokerHandCardsShownEvent.HoleCards#HoleCards.First#PlayingCard", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<int>("Rank")
                                        .HasColumnType("int");

                                    b2.Property<int>("Suit")
                                        .HasColumnType("int");
                                });

                            b1.ComplexProperty<Dictionary<string, object>>("Second", "PokerTrackerApi.Domain.PokerHand.Events.PokerHandCardsShownEvent.HoleCards#HoleCards.Second#PlayingCard", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<int>("Rank")
                                        .HasColumnType("int");

                                    b2.Property<int>("Suit")
                                        .HasColumnType("int");
                                });
                        });

                    b.HasDiscriminator().HasValue("CardsShown");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandCashDropEvent", b =>
                {
                    b.HasBaseType("PokerTrackerApi.Domain.PokerHand.Events.PokerHandEvent");

                    b.Property<decimal>("AmountBB")
                        .HasColumnType("decimal(65,30)");

                    b.HasDiscriminator().HasValue("CashDrop");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandPlayerActionEvent", b =>
                {
                    b.HasBaseType("PokerTrackerApi.Domain.PokerHand.Events.PokerHandEvent");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.ToTable("PokerHandEvents", t =>
                        {
                            t.Property("PlayerId")
                                .HasColumnName("PokerHandPlayerActionEvent_PlayerId");
                        });

                    b.HasDiscriminator().HasValue("PokerHandPlayerActionEvent");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandPostEvent", b =>
                {
                    b.HasBaseType("PokerTrackerApi.Domain.PokerHand.Events.PokerHandEvent");

                    b.Property<decimal>("AmountBB")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("PostType")
                        .HasColumnType("int");

                    b.ToTable("PokerHandEvents", t =>
                        {
                            t.Property("AmountBB")
                                .HasColumnName("PokerHandPostEvent_AmountBB");

                            t.Property("PlayerId")
                                .HasColumnName("PokerHandPostEvent_PlayerId");
                        });

                    b.HasDiscriminator().HasValue("PokerHandPostEvent");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandPotAwardedEvent", b =>
                {
                    b.HasBaseType("PokerTrackerApi.Domain.PokerHand.Events.PokerHandEvent");

                    b.Property<decimal>("AmountBB")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.ToTable("PokerHandEvents", t =>
                        {
                            t.Property("AmountBB")
                                .HasColumnName("PokerHandPotAwardedEvent_AmountBB");

                            t.Property("PlayerId")
                                .HasColumnName("PokerHandPotAwardedEvent_PlayerId");
                        });

                    b.HasDiscriminator().HasValue("PotAwarded");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandUncalledBetReturnedEvent", b =>
                {
                    b.HasBaseType("PokerTrackerApi.Domain.PokerHand.Events.PokerHandEvent");

                    b.Property<decimal>("AmountBB")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.ToTable("PokerHandEvents", t =>
                        {
                            t.Property("AmountBB")
                                .HasColumnName("PokerHandUncalledBetReturnedEvent_AmountBB");

                            t.Property("PlayerId")
                                .HasColumnName("PokerHandUncalledBetReturnedEvent_PlayerId");
                        });

                    b.HasDiscriminator().HasValue("UncalledBetReturned");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandFlopDealtEvent", b =>
                {
                    b.HasBaseType("PokerTrackerApi.Domain.PokerHand.Events.PokerHandBoardDealtEvent");

                    b.ComplexProperty<Dictionary<string, object>>("First", "PokerTrackerApi.Domain.PokerHand.Events.PokerHandFlopDealtEvent.First#PlayingCard", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Rank")
                                .HasColumnType("int");

                            b1.Property<int>("Suit")
                                .HasColumnType("int");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Second", "PokerTrackerApi.Domain.PokerHand.Events.PokerHandFlopDealtEvent.Second#PlayingCard", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Rank")
                                .HasColumnType("int");

                            b1.Property<int>("Suit")
                                .HasColumnType("int");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Third", "PokerTrackerApi.Domain.PokerHand.Events.PokerHandFlopDealtEvent.Third#PlayingCard", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Rank")
                                .HasColumnType("int");

                            b1.Property<int>("Suit")
                                .HasColumnType("int");
                        });

                    b.HasDiscriminator().HasValue("FlopDealt");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandRiverDealtEvent", b =>
                {
                    b.HasBaseType("PokerTrackerApi.Domain.PokerHand.Events.PokerHandBoardDealtEvent");

                    b.ComplexProperty<Dictionary<string, object>>("Card", "PokerTrackerApi.Domain.PokerHand.Events.PokerHandRiverDealtEvent.Card#PlayingCard", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Rank")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("int");

                            b1.Property<int>("Suit")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("int");
                        });

                    b.HasDiscriminator().HasValue("RiverDealt");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandTurnDealtEvent", b =>
                {
                    b.HasBaseType("PokerTrackerApi.Domain.PokerHand.Events.PokerHandBoardDealtEvent");

                    b.ComplexProperty<Dictionary<string, object>>("Card", "PokerTrackerApi.Domain.PokerHand.Events.PokerHandTurnDealtEvent.Card#PlayingCard", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Rank")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("int");

                            b1.Property<int>("Suit")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("int");
                        });

                    b.HasDiscriminator().HasValue("TurnDealt");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandPlayerBetEvent", b =>
                {
                    b.HasBaseType("PokerTrackerApi.Domain.PokerHand.Events.PokerHandPlayerActionEvent");

                    b.Property<decimal>("BetAmountBB")
                        .HasColumnType("decimal(65,30)");

                    b.ToTable("PokerHandEvents", t =>
                        {
                            t.Property("PlayerId")
                                .HasColumnName("PokerHandPlayerActionEvent_PlayerId");
                        });

                    b.HasDiscriminator().HasValue("PlayerBet");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandPlayerCallEvent", b =>
                {
                    b.HasBaseType("PokerTrackerApi.Domain.PokerHand.Events.PokerHandPlayerActionEvent");

                    b.Property<decimal>("CallAmountBB")
                        .HasColumnType("decimal(65,30)");

                    b.ToTable("PokerHandEvents", t =>
                        {
                            t.Property("PlayerId")
                                .HasColumnName("PokerHandPlayerActionEvent_PlayerId");
                        });

                    b.HasDiscriminator().HasValue("PlayerCall");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandPlayerCheckEvent", b =>
                {
                    b.HasBaseType("PokerTrackerApi.Domain.PokerHand.Events.PokerHandPlayerActionEvent");

                    b.ToTable("PokerHandEvents", t =>
                        {
                            t.Property("PlayerId")
                                .HasColumnName("PokerHandPlayerActionEvent_PlayerId");
                        });

                    b.HasDiscriminator().HasValue("PlayerCheck");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandPlayerFoldEvent", b =>
                {
                    b.HasBaseType("PokerTrackerApi.Domain.PokerHand.Events.PokerHandPlayerActionEvent");

                    b.ToTable("PokerHandEvents", t =>
                        {
                            t.Property("PlayerId")
                                .HasColumnName("PokerHandPlayerActionEvent_PlayerId");
                        });

                    b.HasDiscriminator().HasValue("PlayerFold");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandPlayerRaiseEvent", b =>
                {
                    b.HasBaseType("PokerTrackerApi.Domain.PokerHand.Events.PokerHandPlayerActionEvent");

                    b.Property<bool>("IsAllIn")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("RaiseAmountBB")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("RaiseToAmountBB")
                        .HasColumnType("decimal(65,30)");

                    b.ToTable("PokerHandEvents", t =>
                        {
                            t.Property("PlayerId")
                                .HasColumnName("PokerHandPlayerActionEvent_PlayerId");
                        });

                    b.HasDiscriminator().HasValue("PlayerRaise");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandAntePostEvent", b =>
                {
                    b.HasBaseType("PokerTrackerApi.Domain.PokerHand.Events.PokerHandPostEvent");

                    b.ToTable("PokerHandEvents", t =>
                        {
                            t.Property("AmountBB")
                                .HasColumnName("PokerHandPostEvent_AmountBB");

                            t.Property("PlayerId")
                                .HasColumnName("PokerHandPostEvent_PlayerId");
                        });

                    b.HasDiscriminator().HasValue("AntePost");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandBigBlindPostEvent", b =>
                {
                    b.HasBaseType("PokerTrackerApi.Domain.PokerHand.Events.PokerHandPostEvent");

                    b.ToTable("PokerHandEvents", t =>
                        {
                            t.Property("AmountBB")
                                .HasColumnName("PokerHandPostEvent_AmountBB");

                            t.Property("PlayerId")
                                .HasColumnName("PokerHandPostEvent_PlayerId");
                        });

                    b.HasDiscriminator().HasValue("BigBlindPost");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandSmallBlindPostEvent", b =>
                {
                    b.HasBaseType("PokerTrackerApi.Domain.PokerHand.Events.PokerHandPostEvent");

                    b.ToTable("PokerHandEvents", t =>
                        {
                            t.Property("AmountBB")
                                .HasColumnName("PokerHandPostEvent_AmountBB");

                            t.Property("PlayerId")
                                .HasColumnName("PokerHandPostEvent_PlayerId");
                        });

                    b.HasDiscriminator().HasValue("SmallBlindPost");
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.Events.PokerHandEvent", b =>
                {
                    b.HasOne("PokerTrackerApi.Domain.PokerHand.PokerHand", null)
                        .WithMany("Events")
                        .HasForeignKey("HandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.PokerHand", b =>
                {
                    b.HasOne("PokerTrackerApi.HandImports.RawHand", null)
                        .WithOne()
                        .HasForeignKey("PokerTrackerApi.Domain.PokerHand.PokerHand", "HandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.PokerHandPlayer", b =>
                {
                    b.HasOne("PokerTrackerApi.Domain.PokerHand.PokerHand", null)
                        .WithMany("Players")
                        .HasForeignKey("HandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokerTrackerApi.PreflopSpots.PreflopSpot", b =>
                {
                    b.HasOne("PokerTrackerApi.HandImports.RawHand", null)
                        .WithMany()
                        .HasForeignKey("HandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokerTrackerApi.Domain.PokerHand.PokerHand", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
