// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokerTrackerApi.Persistence;

#nullable disable

namespace PokerTrackerApi.Persistence.Migrations
{
    [DbContext(typeof(PokerTrackerDbContext))]
    [Migration("20261002153717_AddHandReplayEntities")]
    partial class AddHandReplayEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PokerTrackerApi.HandHistories.HandHistorySummary", b =>
                {
                    b.Property<string>("HandId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("HeroPosition")
                        .HasColumnType("int");

                    b.ComplexProperty<Dictionary<string, object>>("HoleCards", "PokerTrackerApi.HandHistories.HandHistorySummary.HoleCards#HoleCards", b1 =>
                        {
                            b1.IsRequired();

                            b1.ComplexProperty<Dictionary<string, object>>("First", "PokerTrackerApi.HandHistories.HandHistorySummary.HoleCards#HoleCards.First#PlayingCard", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<int>("Rank")
                                        .HasColumnType("int");

                                    b2.Property<int>("Suit")
                                        .HasColumnType("int");
                                });

                            b1.ComplexProperty<Dictionary<string, object>>("Second", "PokerTrackerApi.HandHistories.HandHistorySummary.HoleCards#HoleCards.Second#PlayingCard", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<int>("Rank")
                                        .HasColumnType("int");

                                    b2.Property<int>("Suit")
                                        .HasColumnType("int");
                                });
                        });

                    b.HasKey("HandId");

                    b.ToTable("HandHistorySummaries");
                });

            modelBuilder.Entity("PokerTrackerApi.HandImport.RawHand", b =>
                {
                    b.Property<string>("HandId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("HandId");

                    b.ToTable("RawHands");
                });

            modelBuilder.Entity("PokerTrackerApi.HandReplays.HandReplayEvent", b =>
                {
                    b.Property<string>("HandId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<decimal?>("AmountBB")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("PlayerId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("RaiseToAmountBB")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.HasKey("HandId", "Sequence");

                    b.ToTable("HandReplayEvents");
                });

            modelBuilder.Entity("PokerTrackerApi.HandReplays.HandReplayEventCard", b =>
                {
                    b.Property<string>("HandId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<int>("CardIndex")
                        .HasColumnType("int");

                    b.ComplexProperty<Dictionary<string, object>>("Card", "PokerTrackerApi.HandReplays.HandReplayEventCard.Card#PlayingCard", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Rank")
                                .HasColumnType("int");

                            b1.Property<int>("Suit")
                                .HasColumnType("int");
                        });

                    b.HasKey("HandId", "Sequence", "CardIndex");

                    b.ToTable("HandReplayEventCards");
                });

            modelBuilder.Entity("PokerTrackerApi.HandReplays.HandReplayPlayer", b =>
                {
                    b.Property<string>("HandId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("PlayerId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<decimal>("StartingStackBB")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("HandId", "PlayerId");

                    b.ToTable("HandReplayPlayers");
                });

            modelBuilder.Entity("PokerTrackerApi.PreflopSpots.PreflopSpot", b =>
                {
                    b.Property<string>("HandId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("SpotKey")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("HandKey")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.HasKey("HandId", "SpotKey");

                    b.HasIndex("SpotKey", "HandKey", "Action");

                    b.ToTable("PreflopSpots");
                });

            modelBuilder.Entity("PokerTrackerApi.HandHistories.HandHistorySummary", b =>
                {
                    b.HasOne("PokerTrackerApi.HandImport.RawHand", null)
                        .WithOne()
                        .HasForeignKey("PokerTrackerApi.HandHistories.HandHistorySummary", "HandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokerTrackerApi.HandReplays.HandReplayEvent", b =>
                {
                    b.HasOne("PokerTrackerApi.HandImport.RawHand", null)
                        .WithMany()
                        .HasForeignKey("HandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokerTrackerApi.HandReplays.HandReplayEventCard", b =>
                {
                    b.HasOne("PokerTrackerApi.HandReplays.HandReplayEvent", null)
                        .WithMany()
                        .HasForeignKey("HandId", "Sequence")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokerTrackerApi.HandReplays.HandReplayPlayer", b =>
                {
                    b.HasOne("PokerTrackerApi.HandImport.RawHand", null)
                        .WithMany()
                        .HasForeignKey("HandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokerTrackerApi.PreflopSpots.PreflopSpot", b =>
                {
                    b.HasOne("PokerTrackerApi.HandImport.RawHand", null)
                        .WithMany()
                        .HasForeignKey("HandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
